from copy import deepcopy
from pathlib import Path


# Define the shared project roots used by the pipeline and notebooks.
research_dir = '/Users/juliomorales/Research/Projects'
project_dir = '/Users/juliomorales/Library/CloudStorage/GoogleDrive-juliomorales1823@gmail.com/My Drive/Graduate School/Research/Projects/Helioseismology/Morales_2025a'

# Define the default output directories for data products and figures.
data_output_dir = f'{project_dir}/Data/Time-Distance'
figure_dir = f'{project_dir}/Morales 2025a et al/Figures/'
animation_dir = f'{figure_dir}Animations/'

# Define the reference data locations used by the default paired-cube configuration.
vesa_2025_dir = '/Users/juliomorales/Library/CloudStorage/GoogleDrive-juliomorales1823@gmail.com/My Drive/Graduate School/Research/Projects/Helioseismology/Vesa_2025/Data/25Apr2019'
vesa_2025_magnetogram = f'{vesa_2025_dir}/25Apr2019.HMImag.ibis.aligned.fits'
co5bold_dir = f'{research_dir}/Morales_2025a/Data/co5bold/hx/10G'
model_atmosphere_path = f'{project_dir}/Data/Time-Distance/model_atmosphere.dat'


# Select the default runtime mode when this module is imported directly.
source_type = 'paired_cubes'  # options: paired_cubes, single_cube


# Store the default observational inputs for paired FITS cubes.
paired_cubes_inputs = {
    'v1_path': f'{vesa_2025_dir}/25Apr2019.ibis.to.hmi.vel.k7699.fits',
    'v2_path': f'{vesa_2025_dir}/25Apr2019.ibis.to.hmi.vel.fe7090.fits',
    'delta_z_km': 168,  # Physical height separation between the paired diagnostics.
    'p_dx_Mm': 68.8 / 160.0,
    'dt': 11.88,
}


# Store the default simulation inputs for a single NetCDF cube.
single_cube_inputs = {
    'file_path': f'{co5bold_dir}/simulation_hx_10G_33570s_48000s.nc',
    'observable': 'v3',  # options: v1, v2, v3, bb1, bb2, bb3, rho
    'h1': 2,
    'h2': 3,
    'model_atmosphere_path': model_atmosphere_path,
}


# Define the default filtering sequence and the per-filter settings.
default_filtering = {
    'enabled': True,
    'filter_sequence': ['magnetogram', 'gaussian'],
    'gaussian': {
        'enabled': True,
        'central_k': 2.0,
        'width_k': 2.0,
        'central_f': 1.5,
        'width_f': 1.5,
    },
    'magnetogram': {
        'enabled': True,
        'magnetogram_v1': vesa_2025_magnetogram,
        'magnetogram_v2': vesa_2025_magnetogram,
        'selection': 'nonmagnetic',
        'threshold_G': 10.0,
        'fill_value': 0.0,
    },
}


# Define the default time-distance geometry and runtime settings.
default_time_distance = {
    'width': 0,
    'dx_pixels': 1.0,
    'nworkers': 12,
    'maxdist_Mm': 10.0,
}


# Define which analysis plots should be generated by default.
default_plot_generate = {
    'cross_correlation': True,
    'phase_difference': True,
    'komega': True,
    'gaussian_filter': True,
    'dopplergram': True,
    'composite': True,
    'correlation_radius_animation': False,
    'correlation_vertical_animation': False,
    'phase_radius_animation': False,
    'phase_vertical_animation': False,
}


def _normalize_source_type(source_type_value):

    '''
    Purpose
    -------
    Normalize the configured source-type label to the canonical runtime name.

    Inputs
    ------
    source_type_value: object
        Raw source-type value from the configuration module.

    Outputs
    -------
    normalized_source_type: str
        Canonical source-type label used by the pipeline.

    Author(s)
    ---------
    Julio M. Morales, March 22nd, 2026.
    '''

    # Normalize the label before validating it downstream.
    normalized_source_type = str(source_type_value).strip().lower()

    # Preserve compatibility with the older single-cube alias.
    if normalized_source_type == 'single_netcdf_cube':
        return 'single_cube'

    return normalized_source_type


def _require(raw_value, field_name):

    '''
    Purpose
    -------
    Enforce that a required configuration value is present.

    Inputs
    ------
    raw_value: object
        Candidate value to validate.

    field_name: str
        Name used in the error message when the value is missing.

    Outputs
    -------
    validated_value: object
        The original value when it is present.

    Author(s)
    ---------
    Julio M. Morales, March 22nd, 2026.
    '''

    # Reject empty values before the pipeline starts building paths or casts.
    if raw_value in ['', None]:
        raise ValueError(f'{field_name} is required.')

    return raw_value


def _normalize_path(path_like):

    '''
    Purpose
    -------
    Expand a path-like input to a normalized user path string.

    Inputs
    ------
    path_like: str or pathlib.Path
        Path value from the configuration inputs.

    Outputs
    -------
    normalized_path: str
        Expanded path string.

    Author(s)
    ---------
    Julio M. Morales, March 22nd, 2026.
    '''

    # Expand `~` so all downstream code receives concrete paths.
    return str(Path(path_like).expanduser())


def get_config(
    source_type,
    v1_path = None,
    v2_path = None,
    delta_z_km = None,
    p_dx_Mm = None,
    dt = None,
    file_path = None,
    observable = None,
    h1 = None,
    h2 = None,
    model_atmosphere_path = None,
    *,
    data_output_dir = data_output_dir,
    figure_dir = figure_dir,
    animation_dir = animation_dir,
    filtering = None,
    time_distance = None,
    plot_generate = None,
    magnetogram_v1 = None,
    magnetogram_v2 = None,
):

    '''
    Purpose
    -------
    Build the mode-aware configuration dictionary used by the time-distance pipeline.

    Inputs
    ------
    source_type: str
        Pipeline mode. Supported values are `paired_cubes` and `single_cube`.

    v1_path, v2_path, delta_z_km, p_dx_Mm, dt: optional
        Required inputs when `source_type = 'paired_cubes'`.

    file_path, observable, h1, h2: optional
        Required inputs when `source_type = 'single_cube'`.

    model_atmosphere_path: str or pathlib.Path, optional
        Optional model-atmosphere table for single-cube runs.

    data_output_dir, figure_dir, animation_dir: str or pathlib.Path, optional
        Output directories used by the pipeline and notebooks.

    filtering, time_distance, plot_generate: dict, optional
        Optional overrides for the default runtime settings.

    magnetogram_v1, magnetogram_v2: str or pathlib.Path, optional
        Optional overrides for the magnetogram paths inside the filtering config.

    Outputs
    -------
    config: dict
        Runtime configuration dictionary with normalized paths and mode-specific inputs.

    Author(s)
    ---------
    Julio M. Morales, March 22nd, 2026.
    '''

    # Normalize the mode label before validating the rest of the inputs.
    source_type = _normalize_source_type(source_type)

    # Reject unsupported modes early so the error is explicit.
    if source_type not in ['paired_cubes', 'single_cube']:
        raise ValueError("source_type must be either 'paired_cubes' or 'single_cube'.")

    # Copy the defaults so callers can override nested settings safely.
    filtering_config = deepcopy(default_filtering if filtering is None else filtering)
    time_distance_config = deepcopy(default_time_distance if time_distance is None else time_distance)
    plot_generate_config = deepcopy(default_plot_generate if plot_generate is None else plot_generate)

    # Ensure the magnetogram section exists before applying path overrides.
    filtering_config.setdefault('magnetogram', {})

    # Apply optional magnetogram-path overrides at the top level for convenience.
    if magnetogram_v1 not in ['', None]:
        filtering_config['magnetogram']['magnetogram_v1'] = _normalize_path(magnetogram_v1)
    if magnetogram_v2 not in ['', None]:
        filtering_config['magnetogram']['magnetogram_v2'] = _normalize_path(magnetogram_v2)

    # Build the shared runtime structure used by both source modes.
    config = {
        'paths': {
            'project_dir': project_dir,
            'data_output_dir': _normalize_path(data_output_dir),
            'figure_dir': _normalize_path(figure_dir),
            'animation_dir': _normalize_path(animation_dir),
        },
        'data': {
            'source_type': source_type,
            'paired_cubes': {},
            'single_cube': {},
            'outfile': '',
            'phase_outfile': '',
            'komega_outfile': '',
            'orientation_validation_outfile': '',
        },
        'filtering': filtering_config,
        'time_distance': time_distance_config,
        'plots': {
            'generate': plot_generate_config,
        },
    }

    # Populate the paired-cube settings and validate the required physical inputs.
    if source_type == 'paired_cubes':
        v1_path = _normalize_path(_require(v1_path, 'v1_path'))
        v2_path = _normalize_path(_require(v2_path, 'v2_path'))
        delta_z_km = float(_require(delta_z_km, 'delta_z_km'))
        p_dx_Mm = float(_require(p_dx_Mm, 'p_dx_Mm'))
        dt = float(_require(dt, 'dt'))

        # Enforce the basic physical constraints expected by the pipeline.
        if delta_z_km < 0.0:
            raise ValueError('delta_z_km must be non-negative.')
        if p_dx_Mm <= 0.0:
            raise ValueError('p_dx_Mm must be positive.')
        if dt <= 0.0:
            raise ValueError('dt must be positive.')

        # Store the resolved paired-cube inputs in the runtime config.
        config['data']['paired_cubes'] = {
            'data_dir': str(Path(v1_path).expanduser().parent),
            'v1': v1_path,
            'v2': v2_path,
            'delta_z_km': delta_z_km,
            'p_dx_Mm': p_dx_Mm,
            'dt': dt,
        }
    else:
        # Populate the single-cube inputs and enforce index-style height selection.
        file_path = _normalize_path(_require(file_path, 'file_path'))
        observable = str(_require(observable, 'observable')).strip()
        h1 = int(_require(h1, 'h1'))
        h2 = int(_require(h2, 'h2'))

        # Reject empty observables and negative layer indices before runtime inference.
        if observable == '':
            raise ValueError('observable is required.')
        if h1 < 0 or h2 < 0:
            raise ValueError('h1 and h2 must be non-negative indices.')

        # Store the resolved single-cube inputs in the runtime config.
        config['data']['single_cube'] = {
            'file': file_path,
            'observable': observable,
            'h1': h1,
            'h2': h2,
        }

        # Include the optional model atmosphere only when the caller provided it.
        if model_atmosphere_path not in ['', None]:
            config['data']['single_cube']['model_atmosphere_path'] = _normalize_path(model_atmosphere_path)

    return config


# Build the default exported config object for direct imports and notebooks.
config = get_config(
    source_type = source_type,
    **(deepcopy(paired_cubes_inputs) if _normalize_source_type(source_type) == 'paired_cubes' else deepcopy(single_cube_inputs)),
)
